### ISSUE TITLE
Array error

### ISSUE THREAD

**Issue by DillFrescott** [auspicious3000/SpeechSplit#64]
What does this mean?

--------------------------------------
make_spect_f0.py:15: FutureWarning: Pass sr=16000, n_fft=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel_basis = mel(16000, 1024, fmin=90, fmax=7600, n_mels=80).T
Found directory: assets/wavs
p226
Traceback (most recent call last):
  File "make_spect_f0.py", line 53, in <module>
    x = np.concatenate((x, np.array([1e-06])), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Comment by DillFrescott** [comment]
Nevermind I think it means they have to be mono
